#!/bin/bash

while read url
do

  wgetProgram=wget
  urlCmd="$url?command=full-import&clean=false"
  statusCmd="$url?command=status"
  outputDir=.

  $wgetProgram -O $outputDir/status_update_index.txt ${urlCmd} 2>/dev/null

  while [ true ]; do
  $wgetProgram -O $outputDir/check_status_update_index.txt ${statusCmd} 2>/dev/null
  
  if [ $? -eq 4 ]
  then
    break
  fi

  status=`fgrep idle $outputDir/check_status_update_index.txt`

  if [[ ${status} == *idle* ]] 
  then
    #echo "Update-index DONE"
    break
  fi
  sleep 10
  done
done < $1
